#!/bin/bash
augOptParse()
{
	read -p "number > " id
	if [ -z "$id" ]; then
		augOptParse
	fi
}

augBuild()
{
	local str="--------------------------------"
	str+="\nRunning benchmark on $bench"
	str+="\n-----------------------------------"
	echo -e "$str"
	source "$__benchdir/$bench"		
}

augBench()
{
	local __file="${BASH_SOURCE[0]}"
	local __dir="$(cd "$( dirname "$__file" )" && pwd )"
	local __benchdir=$(find "$(pwd)" -type d -name "benchmarks")
	if [ -z "$__benchdir" ]; then
		echo -e "\033[1;31mCould not locate test benchmark directory!!!\033[1;m"
		exit 1
	fi
	local __filepath="$__dir${__file:1}"
	local bench=''
	local id=''
	local args="$@"
	if [ -z "$args" ]; then
		echo 'Please choose a file to time:'
		local count=1
		local files=($(ls "$__benchdir"))
	    for file in ${files[@]}; do
			echo -en "$count: $file\t\n"
			count=$[ $count + 1 ]
		done
		augOptParse
		bench=${files["$id-1"]}
	else
		bench=$1
	fi

	augBuild
}

augBench $@
exit 0

