#!/usr/bin/python

import sys
from timeit import Timer

def run():
	stat = Timer("subprocess.call(['./bake', '-df', '%s'])" % sys.argv[1], 'import subprocess').repeat(repeat=6, number=1)
	print(stat)
	return 0
	

if "__main__" == __name__:
	sys.exit(run())


